project:
  type: website
  output-dir: _site
  render:
    - pages/index.qmd
    - pages/about.qmd
    - notebooks/model-vetiver.qmd
    - "!eda-db.qmd"
    - "!model-basic-py.qmd"
    - "!model-db.qmd"
    - "!app-*.R"
    - "!my-db.duckdb"

website:
  title: "Penguin Explorer"
  navbar:
    left:
      - text: "Home"
        href: pages/index.qmd
      - text: "About"
        href: pages/about.qmd
      - text: "Model"
        href: notebooks/model-vetiver.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
