project:
  type: website
  output-dir: _site
  render:
    - index.qmd
    - about.qmd
    - model-vetiver.qmd
    - "!eda-db.qmd"
    - "!model-basic-py.qmd"
    - "!model-db.qmd"
    - "!app-*.R"
    - "!my-db.duckdb"

website:
  title: "Penguin Explorer"
  navbar:
    left:
      - text: "Home"
        file: pages/index.qmd
      - text: "About"
        file: pages/about.qmd
      - text: "Model"
        file: notebooks/model-vetiver.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
